module.exports = Object.freeze({
quiz_data:
{
  "decadeImg":["https://physeek.fit/tools/asmm/decadesvin.png",  
              "https://physeek.fit/tools/asmm/decades.png"],
  "60s": {
    "name": "Swinging Sixties",
    "startMsg": "We start our four decade musical journey starting from the Swinging Sixties",
    "bkgimgurl": "https://physeek.fit/tools/asmm/60s.png",
    "bands": [
      "The Beatles",
"The Rolling Stones",
"Jefferson Airplane",
"Cream",
"Pink Floyd",
"Simon AND Garfunkel",
"The Byrds",
"Creedence Clearwater Revival",
"The Jimi Hendrix Experience",
"The Beach Boys",
"The Who",
"The Kinks",
"The Doors",
"The Yardbirds",
"The Moody Blues",
"The Animals",
"The Mamas and the Papas",
"The Velvet Underground",
"The Shadows",
"The Grateful Dead",
"The Ventures",
"The Loving Spoonfull",
"Hermans Hermits",
"The Hollies",
"Country Joe and the Fish",
"Steppenwolf",
"Gerry and the Pacemakers",
"The Troggs",
"The Mothers of Invention",
"Paul Revere AND the Raiders",
"The Flying Burrito Brothers",
"Led Zeppelin",
"Vanilla Fudge",
"Ten Years After",
"The Holy Modal Rounders",
"Fleetwood Mac",
"The Monkees",
"Nitty Gritty Dirt Band",
"King Crimson",
"The Spencer Davis Group",
"Moby Grape",
"Procol Harum",
"The Great Society",
"The Incredible String Band",
"Them",
"Deep Purple",
"Big Brother AND the Holding Company",
"The Kingsmen",
"Fairport Convention",
"Iron Butterfly",
"Canned Heat",
"The Amboy Dukes",
"Pretty Things",
"Steve Miller Band",
"The Band",
"John Mayall AND the Bluesbreakers",
"Soft Machine",
"Jethro Tull",
"The Butterfield Blues Band",
"The Guess Who",
"Savoy Brown",
"Buffalo Springfield",
"Santana",
"The Music Machine",
"The Jeff Beck Group",
"The Nice",
"Manfred Mann",
"The h Floor Elevators",
"Love",
"Traffic",
"Captain Beefheart and his Magic Band",
"Family",
"Colosseum",
"Sly and the Family Stone",
"Blue Cheer",
"The Electric Prunes",
"Spirit",
"Free",
"Crosby, Still, Nash AND Young",
"The Seeds",
"Jan and Dean",
"Question Mark and the Mysterians",
"The West Coast Pop Art Experimental Band",
"The Shadows of Knight",
"Small Faces",
"The Zombies",
"Blind Faith",
"The Easybeats",
"The Grass Roots",
"Sir Douglas Quintet",
"Quicksilver Messenger Service",
"MC5",
"Humble Pie",
"The Charlatans",
"Strawberry Alarm Clock",
"The Youngbloods",
"Jay and the Americans",
"The Fabulous Wailers",
"Stone Poneys",
"The Syndicate of Sound"
    ],
    "trivia": [
      "I want to hold your hand gave The Beatles their first US No.1 hit",
      "The 1966 US No.1 hit 96 Tears was scored by Question Mark and the Mysterians",
      "Phil Spector invented the music production technique called The Wall of Sound in the 1960s",
      "Hello, I’m Dolly was debut album of Dolly Parton in 1967",
      "The band was formed by Jack Bruce, Eric Clapton, and Ginger Baker in the 1960s was called Cream",
      "In 1961, the famous singer Frank Sinatra established Reprise Records",
      "Top of the Pops was a famous music first launched on the BBC on 1st January 1964?",
      "U.S rock singer Jimi Hendrix had their final performance at the 1969 Woodstock festival",
      "“It’s Now or Never” was the first number one of Elvis Presley in the 1960s",
      "Dolly Parton was the female singer known as the face of the 60s country music",
      "A genre that became exceedingly popular in the ‘60s was blues rock. The genre combined blues with rock music to form eclectic compositions that experimented with new sonic elements. Although a number of bands came form the blues scene in the mid-'60s, every band had a different approach to instrumentation and lyricism.",
      "Blues rock bands from the U.K. and the U.S. became hugely popular, gaining large, devoted audiences. The genre played a pivotal role in paving the way for the Southern rock, hard rock, and heavy metal genres of the ‘70s. Extended boogie jams often played around the twelve-bar blues were a notable feature in blues rock. The heavy riff-oriented sound was characterized by bluesy improvised solos played at faster tempos than traditional blues songs.",
      "The advent of the television talk show gave many bands the opportunity to reach large audiences in the '60s.",
      "While most bands in this genre were rooted in blues, folk, and jazz, other bands adopted elements of Indian classical music, forming a hybrid sound called raga rock. Long improvisational instrumental segments were a noteworthy part of this rock experience."


    ]
  },
  "70s": {
    "name": "Super Seventies",
    "startMsg": "As we continue our journey, we now enter the Super Seventies",
    "bkgimgurl": "https://physeek.fit/tools/asmm/70s.jpg",
    "bands": [
     "Led Zeppelin",
"Deep Purple",
"Black Sabbath",
"The Who",
"The Eagles",
"The Doors",
"Pink Floyd",
"The Rolling Stones",
"The Allman Brothers Band",
"The Mothers of Invention",
"Kansas",
"Blue Oyster Cult",
"King Crimson",
"Queen",
"Styx",
"Lynyrd Skynyrd",
"AC/DC",
"Fleetwood Mac",
"Jethro Tull",
"Rush",
"Bad Company",
"Journey",
"Blood, Sweat and Tears",
"Genesis",
"Chicago",
"Emerson, Lake AND Palmer",
"Thin Lizzy",
"America",
"Bee Gees",
"Grateful Dead",
"Nazareth",
"The Moody Blues",
"Steely Dan",
"Captain Beefheart and His Magic Band",
"The Marshall Tucker Band",
"The Byrds",
"Roxy Music",
"Kiss",
"Electric Light Orchestra",
"Supertramp",
"The Ozark Mountain Daredevils",
"Wings",
"Caravan",
"Sweet",
"Mott The Hoople",
"The Flying Burrito Brothers",
"Bread",
"T. Rex",
"Aerosmith",
"Judas Priest",
"Boston",
"Heart",
"Motorhead",
"Creedence Clearwater Revival",
"Uriah Heep",
"Blondie",
"Santana",
"Foreigner",
"ZZ Top",
"The Beach Boys",
"Gong",
"Steve Miller Band",
"The Kinks",
"REO Speedwagon",
"Soft Machine",
"The Doobie Brothers",
"Mud",
"Can",
"Grand Funk Railroad",
"The Ramones",
"Hall AND Oates",
"Slade",
"Crosby, Stills AND Nash",
"Focus",
"Alice Cooper",
"Talking Heads",
"Wishbone Ash",
"The Police",
"Hawkwind",
"The Sex Pistols",
"Camel",
"The Velvet Underground",
"The Cars",
"Seals AND Croft",
"Gentle Giant",
"The Clash",
"Budgie",
"Status Quo",
"Traffic",
"Badfinger",
"UFO",
"Foghat",
"Dire Straits",
"The Guess Who",
"XTC",
"Scorpions",
"Golden Earring",
"Funkadelic",
"The Stooges"

    ],
    "trivia": [
      "In 1972, Seals and Croft felt fine in the Summer season",
      "In her song Killing Me Softly Roberta Flack is paying tribute to Don McLean",
      "Steely Dan was Reelin in the Years back in 1972",
      "In Brown Sugar by The Rolling Stones, slaves were sold in New Orleans",
      "In Love Train by The O’Jays, they call all the people in Africa",
      "Johnny Cash wrote and produced the 1971 hit Man in Black",
      "Rumors was the 1977 best-selling album by Fleetwood Mac",
      "I hope someday you'll join us, and the world will be as one are lines from the John Lennon's famous song - Imagine",
      "Aerosmith was rock band formed in Boston in 1970, that included Joey Kramer, Brad Whitford, Tom Hamilton, Joe Perry, and Steven Tyler.",
      "Sticky Fingers is a 1971 album released by The Rolling Stones",
      "In the '70s, a number of bands started experimenting with synthesizers, bringing about a musical revolution.",
      "Progressive rock spread its roots far and wide in the '70s. Certain bands played a pivotal role in shaping the future of experimental rock.",
      "Glam rock was all the rage in the '70s adapting the guitar-driven sound of hard rock along with a theatrical blend of science fiction references and operatic influences."

    ]
  },
  "80s": {
    "name": "Mighty Eighties",
    "startMsg": "Our journey has now reached the Mighty Eighties",
    "bkgimgurl": "https://physeek.fit/tools/asmm/80s.jpg",
    "bands": [
      "Guns N’ Roses",
"Queen",
"Metallica",
"AC/DC",
"Bon Jovi",
"Foreigner",
"Journey",
"Motorhead",
"R.E.M.",
"U2",
"Judas Priest",
"Van Halen",
"Whitesnake",
"Def Leppard",
"REO Speedwagon",
"Megadeth",
"Iron Maiden",
"The Police",
"ZZ Top",
"Aerosmith",
"Motley Crue",
"Dio",
"Poison",
"Dire Straits",
"Scorpions",
"Heart",
"Tears For Fears",
"Quiet Riot",
"Survivor",
"Europe",
"Kiss",
"Bauhaus",
"New Order",
"Venom",
"The Cure",
"Slayer",
"Black Sabbath",
"Bad Brains",
"Cinderella",
"The Psychedelic Furs",
"Anthrax",
"Siouxsie and the Banshees",
"Twisted Sister",
"Saxon",
"Dokken",
"The Smiths",
"Exodus",
"Husker Du",
"Chicago",
"Duran Duran",
"Rush",
"The Replacements",
"Sepultura",
"Loverboy",
"A Flock of Seagulls",
"A-ha",
"Love and Rockets",
"Manowar",
"Napalm Death",
"Black Flag",
"Diamond Head",
"The Mekons",
"Primal Scream",
"The Pogues",
"Dead Kennedys",
"Echo and the Bunnymen",
"Toto",
"Red Hot Chili Peppers",
"Testament",
"The Bangles",
"D.O.A.",
"Sonic Youth",
"Death Angel",
"Cocteau Twins",
"Accept",
"Kreator",
"The Ramones",
"America",
"Pantera",
"Suicidal Tendencies",
"My Bloody Valentine",
"Devo",
"Killing Joke",
"Yes",
"Savatage",
"Krokus",
"Violent Femmes",
"Triumph",
"Anvil",
"Dinosaur Jr.",
"Rolling Stones",
"The Cars",
"Pink Floyd",
"Marillion",
"Simple Minds",
"The Clash",
"Fleetwood Mac",
"Asia",
"Blue Oyster Cult"
],
    "trivia": [
      "Blondie ranked at No. 1 on the Billboard Year-End Hot 100 Singles of 1980",
      "In the 1980s, Michael Jackson earned 9 US No. 1 Singles",
      "Boy George was the lead singer of the famous band Culture Club",
      "In 1984, to raise funds for those struck by famine in Ethiopia, Band Aid released the song Do They Know It's Christmas?",
      "Like A Virgin was the single for which Madonna first topped the Billboard Hot 100",
      "Rick Astley topped the charts in 25 countries for the song - Never Gonna Give You Up",
      "Bruce Springsteen penned the famous lyrics - you can't start a fire without a spark",
      "The 80's pop legends A-Ha hail from Norway",
      "Huey Lewis and the News wrote ‘The Power of Love’ for 1985 Hollywood blockbuster Back to the Future",
      "George Michael wrote hit song, Careless Whisper, at the age of 17",
      "Thanks to music television, rock music reached its pinnacle in the ‘80s. MTV, which launched in 1981, showcased a number of mainstream and non-mainstream rock bands.",
    ]
  },
  "90s": {
    "name": "Nostalgic Nineties",
    "startMsg": "Finally, we will now cruise through the Nostalgic Nineties",
    "bkgimgurl": "https://physeek.fit/tools/asmm/90s.jpg",
    "bands": [
      "Nirvana",
"Alice In Chains",
"Soundgarden",
"Green Day",
"Radiohead",
"Pearl Jam",
"R.E.M",
"Foo Fighters",
"Red Hot Chili Peppers",
"Pantera",
"Metallica",
"Guns N' Roses",
"Oasis",
"U2",
"Nine Inch Nails",
"Queen",
"Weezer",
"No Doubt",
"The Offspring",
"The Wallflowers",
"Rage Against The Machine",
"The Cranberries",
"Slayer",
"My Bloody Valentine",
"The Mighty Mighty Bosstones",
"Stone Temple Pilots",
"Korn",
"Pavement",
"Anthrax",
"Blur",
"The Smashing Pumpkins",
"The Verve",
"Pixies",
"Bush",
"Jane's Addiction",
"The Lemonheads",
"The Flaming Lips",
"Goo Goo Dolls",
"Sonic Youth",
"Dream Theater",
"Blind Melon",
"Garbage",
"Megadeth",
"Pulp",
"Aerosmith",
"Faith No More",
"Dave Matthews Band",
"Live",
"Tool",
"Silverchair",
"Counting Crows",
"Emperor",
"Creed",
"Hootie and The Blowfish",
"Bon Jovi",
"Incubus",
"Testament",
"Collective Soul",
"Helmet",
"Sublime",
"Third Eye Blind",
"AC/DC",
"Our Lady Peace",
"Primus",
"Bad Religion",
"Extreme",
"Scorpions",
"Blues Traveller",
"Van Halen",
"Sepultura",
"The Black Crowes",
"Def Leppard",
"Soul Asylum",
"Candlebox",
"Matchbox 20",
"Skid Row",
"The Cardigans",
"White Zombie",
"Spin Doctors",
"Meshuggah",
"311",
"Mudhoney",
"Fear Factory",
"Barenaked Ladies",
"Sleater-Kinney",
"Mr. Big",
"Limp Bizkit",
"Death",
"Firehouse",
"Ministry",
"Semisonic",
"Motorhead",
"Guided By Voices",
"Napalm Death",
"Opeth",
"Warrant",
"Marylin Manson",
"Everclear",
" Crash Test Dummies"
    ],
    "trivia": [
      "Backstreet Boys received their first Gold record in Germany",
      "Elton John rewrote the classic Candle in the Wind as a tribute to Diana, Princess of Wales after her death in 1997",
      "Eddie Vedder was the lead singer of Pearl Jam",
      "TLC was the best-selling girl group of the 1990s in the US",
      "In 1999, Christina Aguilera had a number one hit on the Billboard Hot 100 with Genie In A Bottle",
      "Kurt Cobain was the lead singer/guitarist for the band Nirvana",
      "Metallica released a self titled album in 1991 which was also called The Black Album",
      "Jennifer Lopez named her first album - On the 6",
      "James Hatfield is the lead vocalist and co-founder of heavy metal Metallica",
      "In 1999, For the song Maria, Ricky Martin won Guinness World Records for Biggest Latin Hit"
      
    ]
  }
}

});